/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import defencesystem.Starter;
import enums.Strength;
import interfaces.Obsever;
import javax.swing.JOptionPane;
import utils.SuperDefence;

/**
 *
 * @author 94705
 */
public class Submarine extends SuperDefence implements Obsever{
   private boolean isPosition;
   private String messages = "";
    /**
     * Creates new form Submarine
     */
    public Submarine() {
        initComponents();
        setVisible(true);
        soldiersSpinner.setValue(30);
        ammoSpinner.setValue(120);
        missileSpinner.setValue(70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areClearLabel = new javax.swing.JLabel();
        isPositionCb = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        energySlider = new javax.swing.JSlider();
        soldiersSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ammoSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        missileSpinner = new javax.swing.JSpinner();
        missileBtn = new javax.swing.JButton();
        sonarBtn = new javax.swing.JButton();
        shootBtn = new javax.swing.JButton();
        msgBox = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inboxMsg = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        oxygenSlider = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        torpedoeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Submarine");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        areClearLabel.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N
        areClearLabel.setText("Area Not cleared");

        isPositionCb.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        isPositionCb.setText("Position");
        isPositionCb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                isPositionCbStateChanged(evt);
            }
        });
        isPositionCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isPositionCbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setText("Energy");

        energySlider.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        energySlider.setMajorTickSpacing(20);
        energySlider.setOrientation(javax.swing.JSlider.VERTICAL);
        energySlider.setPaintLabels(true);
        energySlider.setValue(100);
        energySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                energySliderStateChanged(evt);
            }
        });

        soldiersSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                soldiersSpinnerStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setText("Soldiers");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setText("Ammo");

        ammoSpinner.setPreferredSize(new java.awt.Dimension(70, 22));
        ammoSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ammoSpinnerStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel7.setText("Missile");

        missileSpinner.setPreferredSize(new java.awt.Dimension(70, 22));
        missileSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                missileSpinnerStateChanged(evt);
            }
        });

        missileBtn.setText("Missile operations");
        missileBtn.setEnabled(false);
        missileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missileBtnActionPerformed(evt);
            }
        });

        sonarBtn.setText("Sonar operations");
        sonarBtn.setEnabled(false);
        sonarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonarBtnActionPerformed(evt);
            }
        });

        shootBtn.setText("Shoot");
        shootBtn.setEnabled(false);
        shootBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootBtnActionPerformed(evt);
            }
        });

        msgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgBoxActionPerformed(evt);
            }
        });

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        inboxMsg.setEditable(false);
        inboxMsg.setColumns(20);
        inboxMsg.setRows(5);
        jScrollPane1.setViewportView(inboxMsg);

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Send Messages");

        jLabel1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel1.setText("Inbox Messages");

        oxygenSlider.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        oxygenSlider.setMajorTickSpacing(20);
        oxygenSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        oxygenSlider.setPaintLabels(true);
        oxygenSlider.setValue(100);
        oxygenSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                oxygenSliderStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel8.setText("Oxygen");

        torpedoeBtn.setText("Torpedoes");
        torpedoeBtn.setEnabled(false);
        torpedoeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torpedoeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msgBox)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(areClearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isPositionCb))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(sendBtn)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(missileSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soldiersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ammoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4)
                            .addComponent(energySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(oxygenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shootBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(torpedoeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(missileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sonarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areClearLabel)
                            .addComponent(isPositionCb))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(soldiersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ammoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(missileSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(oxygenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(energySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missileBtn)
                    .addComponent(shootBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendBtn)
                    .addComponent(torpedoeBtn)
                    .addComponent(sonarBtn))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isPositionCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isPositionCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isPositionCbActionPerformed

    private void missileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missileBtnActionPerformed
        int value = (int)missileSpinner.getValue();
        value--;
        missileSpinner.setValue(value);
    }//GEN-LAST:event_missileBtnActionPerformed

    private void sonarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sonarBtnActionPerformed

    private void shootBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootBtnActionPerformed
        int value = (int)ammoSpinner.getValue();
        value--;
        ammoSpinner.setValue(value);

    }//GEN-LAST:event_shootBtnActionPerformed

    private void msgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgBoxActionPerformed

    private void torpedoeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torpedoeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_torpedoeBtnActionPerformed

    private void isPositionCbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_isPositionCbStateChanged
        isPosition = isPositionCb.isSelected();
        if(isPosition == false){
            shootBtn.setEnabled(false);
            missileBtn.setEnabled(false);
            torpedoeBtn.setEnabled(false);
            sonarBtn.setEnabled(false);
        }
    }//GEN-LAST:event_isPositionCbStateChanged

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        if(msgBox.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Your Message...", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            Starter.mainController.setMessages(" (Submarine) - "+msgBox.getText());
            msgBox.setText("");
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void soldiersSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_soldiersSpinnerStateChanged
        Starter.mainController.setSubmarineValues(1,(int)soldiersSpinner.getValue());
    }//GEN-LAST:event_soldiersSpinnerStateChanged

    private void ammoSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ammoSpinnerStateChanged
        Starter.mainController.setSubmarineValues(2,(int)ammoSpinner.getValue());
    }//GEN-LAST:event_ammoSpinnerStateChanged

    private void missileSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_missileSpinnerStateChanged
        Starter.mainController.setSubmarineValues(3,(int)missileSpinner.getValue());
    }//GEN-LAST:event_missileSpinnerStateChanged

    private void energySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_energySliderStateChanged
       Starter.mainController.setSubmarineValues(4, energySlider.getValue());
    }//GEN-LAST:event_energySliderStateChanged

    private void oxygenSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_oxygenSliderStateChanged
        Starter.mainController.setSubmarineValues(5, oxygenSlider.getValue());
    }//GEN-LAST:event_oxygenSliderStateChanged

    //==================================================================
    //area clear msg
    @Override
    public void sendAreaClearedMsg(boolean value){
       areClearLabel.setText(value == true?"Area cleared":"Area Not cleard");
    }
     @Override
    public void sendMessages(String message){
        messages += message+"\n";
       inboxMsg.setText(messages);
    }
    
    
    
    //enable options
    @Override
    public void enableOptions(Strength strength){
        shootBtn.setEnabled(false);
        missileBtn.setEnabled(false);
        torpedoeBtn.setEnabled(false);
        sonarBtn.setEnabled(false);
        
        if(isPosition){
            switch(strength){
    //            LOW, MEDIUM, HIGH, STRONG, CLOSED
                case CLOSED:
                    break;
                case LOW:
                    shootBtn.setEnabled(true);
                    break;
                case MEDIUM:
                    shootBtn.setEnabled(true);
                    missileBtn.setEnabled( true);
                    break;
                case HIGH:
                    shootBtn.setEnabled(true);
                    missileBtn.setEnabled( true);
                    torpedoeBtn.setEnabled(true);
                    break;
                case STRONG:
                    shootBtn.setEnabled(true);
                    missileBtn.setEnabled( true);
                    torpedoeBtn.setEnabled(true);
                    sonarBtn.setEnabled(true);
                    break;      
            }
        }
    }
    
    public void setPrivateMessage(String message){
        messages += message+"\n";
        inboxMsg.setText(messages);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ammoSpinner;
    private javax.swing.JLabel areClearLabel;
    private javax.swing.JSlider energySlider;
    private javax.swing.JTextArea inboxMsg;
    private javax.swing.JCheckBox isPositionCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton missileBtn;
    private javax.swing.JSpinner missileSpinner;
    private javax.swing.JTextField msgBox;
    private javax.swing.JSlider oxygenSlider;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton shootBtn;
    private javax.swing.JSpinner soldiersSpinner;
    private javax.swing.JButton sonarBtn;
    private javax.swing.JButton torpedoeBtn;
    // End of variables declaration//GEN-END:variables
}
