/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import defencesystem.Starter;
import enums.Strength;
import interfaces.Obsever;
import javax.swing.JOptionPane;
import utils.SuperDefence;

/**
 *
 * @author 94705
 */
public class Tank extends SuperDefence implements Obsever{
    
    private boolean isPosition;
    private String messages= "";
    /**
     * Creates new form Tank
     */
    public Tank() {
        initComponents();
        setVisible(true);
        soldiersSpinner.setValue(5);
        ammoSpinner.setValue(97);
        missileSpinner.setValue(15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areClearLabel = new javax.swing.JLabel();
        isPositionCb = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        soldiersSpinner = new javax.swing.JSpinner();
        energySlider = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        inboxMsg = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        ammoSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        missileSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        msgBox = new javax.swing.JTextField();
        shootBtn = new javax.swing.JButton();
        missileBtn = new javax.swing.JButton();
        sendBtn = new javax.swing.JButton();
        redarBtn = new javax.swing.JButton();
        rotateShootBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tank");
        setPreferredSize(new java.awt.Dimension(620, 420));
        setResizable(false);

        areClearLabel.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N
        areClearLabel.setText("Area Not cleared");

        isPositionCb.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        isPositionCb.setText("Position");
        isPositionCb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                isPositionCbStateChanged(evt);
            }
        });
        isPositionCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isPositionCbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setText("Energy");

        jLabel1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel1.setText("Inbox Messages");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setText("Soldiers");

        soldiersSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                soldiersSpinnerStateChanged(evt);
            }
        });

        energySlider.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        energySlider.setMajorTickSpacing(20);
        energySlider.setOrientation(javax.swing.JSlider.VERTICAL);
        energySlider.setPaintLabels(true);
        energySlider.setValue(100);
        energySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                energySliderStateChanged(evt);
            }
        });

        inboxMsg.setEditable(false);
        inboxMsg.setColumns(20);
        inboxMsg.setRows(5);
        jScrollPane1.setViewportView(inboxMsg);

        jLabel6.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel6.setText("Ammo");

        ammoSpinner.setPreferredSize(new java.awt.Dimension(70, 22));
        ammoSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ammoSpinnerStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel7.setText("Missile");

        missileSpinner.setPreferredSize(new java.awt.Dimension(70, 22));
        missileSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                missileSpinnerStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Send Messages");

        msgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgBoxActionPerformed(evt);
            }
        });

        shootBtn.setText("Shoot");
        shootBtn.setEnabled(false);
        shootBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootBtnActionPerformed(evt);
            }
        });

        missileBtn.setText("Missile operations");
        missileBtn.setEnabled(false);
        missileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missileBtnActionPerformed(evt);
            }
        });

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        redarBtn.setText("Redar operations");
        redarBtn.setEnabled(false);
        redarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redarBtnActionPerformed(evt);
            }
        });

        rotateShootBtn.setText("Rotate Shoot");
        rotateShootBtn.setEnabled(false);
        rotateShootBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateShootBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(areClearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(isPositionCb))
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(msgBox))
                            .addGap(37, 37, 37)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sendBtn)
                        .addGap(228, 228, 228)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(missileSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soldiersSpinner)
                            .addComponent(ammoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(energySlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(shootBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(missileBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotateShootBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(redarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areClearLabel)
                            .addComponent(isPositionCb))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(soldiersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ammoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(missileSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(energySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missileBtn)
                    .addComponent(shootBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendBtn)
                    .addComponent(rotateShootBtn)
                    .addComponent(redarBtn))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isPositionCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isPositionCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isPositionCbActionPerformed

    private void msgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgBoxActionPerformed

    private void shootBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootBtnActionPerformed
        int value = (int)ammoSpinner.getValue();
        value--;
        ammoSpinner.setValue(value);
    }//GEN-LAST:event_shootBtnActionPerformed

    private void missileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missileBtnActionPerformed
        int value = (int)missileSpinner.getValue();
        value--;
        missileSpinner.setValue(value);
    }//GEN-LAST:event_missileBtnActionPerformed

    private void redarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redarBtnActionPerformed

    private void rotateShootBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateShootBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotateShootBtnActionPerformed

    private void isPositionCbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_isPositionCbStateChanged
        isPosition = isPositionCb.isSelected();
        if(isPosition == false){
            shootBtn.setEnabled(false);
            missileBtn.setEnabled(false);
            rotateShootBtn.setEnabled(false);
            redarBtn.setEnabled(false);

        }
    }//GEN-LAST:event_isPositionCbStateChanged

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        if(msgBox.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Your Message...", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            Starter.mainController.setMessages(" (Tank) - "+msgBox.getText());
        msgBox.setText("");
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void soldiersSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_soldiersSpinnerStateChanged
        Starter.mainController.setTankValues(1,(int)soldiersSpinner.getValue());
    }//GEN-LAST:event_soldiersSpinnerStateChanged

    private void ammoSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ammoSpinnerStateChanged
        Starter.mainController.setTankValues(2,(int)ammoSpinner.getValue());
    }//GEN-LAST:event_ammoSpinnerStateChanged

    private void missileSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_missileSpinnerStateChanged
       Starter.mainController.setTankValues(3,(int)missileSpinner.getValue());
    }//GEN-LAST:event_missileSpinnerStateChanged

    private void energySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_energySliderStateChanged
        Starter.mainController.setTankValues(4,energySlider.getValue());
    }//GEN-LAST:event_energySliderStateChanged

//==================================================================
    //area clear msg
    @Override
    public void sendAreaClearedMsg(boolean value){
        areClearLabel.setText(value == true?"Area cleared":"Area Not cleard");
    }
    
    @Override
    public void sendMessages(String message){
        messages += message+"\n";
       inboxMsg.setText(messages);
    }
    
     public void setPrivateMessage(String message){
        messages += message+"\n";
        inboxMsg.setText(messages);
    }
    
    
    //enable options
    @Override
   public void enableOptions(Strength strength){
        shootBtn.setEnabled(false);
        missileBtn.setEnabled(false);
        rotateShootBtn.setEnabled(false);
        redarBtn.setEnabled(false);
      
        if(isPosition){
        switch(strength){
//            LOW, MEDIUM, HIGH, STRONG, CLOSED
            case CLOSED:
                break;
            case LOW:
                shootBtn.setEnabled(true);
                break;
            case MEDIUM:
                shootBtn.setEnabled(true);
                missileBtn.setEnabled( true);
                break;
            case HIGH:
                shootBtn.setEnabled(true);
                missileBtn.setEnabled( true); 
                rotateShootBtn.setEnabled(true);
                break;
            case STRONG:
                shootBtn.setEnabled(true);
                missileBtn.setEnabled( true);
                rotateShootBtn.setEnabled(true);
                redarBtn.setEnabled(true);
                break;      
        }
    }
   }
   
  
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner ammoSpinner;
    private javax.swing.JLabel areClearLabel;
    private javax.swing.JSlider energySlider;
    private javax.swing.JTextArea inboxMsg;
    private javax.swing.JCheckBox isPositionCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton missileBtn;
    private javax.swing.JSpinner missileSpinner;
    private javax.swing.JTextField msgBox;
    private javax.swing.JButton redarBtn;
    private javax.swing.JButton rotateShootBtn;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton shootBtn;
    private javax.swing.JSpinner soldiersSpinner;
    // End of variables declaration//GEN-END:variables
}
